apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
  namespace: student-j-hofer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi

